import { defineConfig } from 'vite';

export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        main: './index.html',
        login: './src/pages/login/login.html',
        menu: './src/pages/menu/menu.html',
        cart: './src/pages/cart/cart.html',
        
        amarah: './src/pages/menu/amarah/amarah.html',
        pastil: './src/pages/menu/amarah/pastil.html',
        hotdogBuns: './src/pages/menu/amarah/hotdog-buns.html',
        hotdogStick: './src/pages/menu/amarah/hotdog-stick.html',
        mineralWater: './src/pages/menu/amarah/mineral-water.html',
        coke: './src/pages/menu/amarah/coke.html',
        minuteMaid: './src/pages/menu/amarah/minute-maid.html',

        anneSarap: './src/pages/menu/anne-sarap/anne-sarap.html',
        blueLemonade: './src/pages/menu/anne-sarap/blue-lemonade.html',
        icedRedTea: './src/pages/menu/anne-sarap/iced-red-tea.html',
        pineappleJuice: './src/pages/menu/anne-sarap/pineapple-juice.html',
        grapeJuice: './src/pages/menu/anne-sarap/grape-juice.html',
        mangoJuice: './src/pages/menu/anne-sarap/mango-juice.html',
        icedTea: './src/pages/menu/anne-sarap/iced-tea.html',

        cafeFerrer: './src/pages/menu/cafe-ferrer/cafe-ferrer.html',
        teriyaki: './src/pages/menu/cafe-ferrer/teriyaki.html',
        yangnyeom: './src/pages/menu/cafe-ferrer/yangnyeom.html',
        honey: './src/pages/menu/cafe-ferrer/honey-sriracha.html',
        saltedEgg: './src/pages/menu/cafe-ferrer/salted-egg.html',
        garlicParmesan: './src/pages/menu/cafe-ferrer/garlic-parmesan.html',
        spicyBuffalo: './src/pages/menu/cafe-ferrer/spicy-buffalo.html',

        chicksAhoy: './src/pages/menu/chicks-ahoy/chicks-ahoy.html',  
        dynamite: './src/pages/menu/chicks-ahoy/dynamite.html',  
        chow: './src/pages/menu/chicks-ahoy/chow.html', 
        chickenPoppers: './src/pages/menu/chicks-ahoy/chicken-poppers.html', 
        chickenFingers: './src/pages/menu/chicks-ahoy/chicken-fingers.html',
        ahoy: './src/pages/menu/chicks-ahoy/ahoy.html',
        konnichiwa: './src/pages/menu/chicks-ahoy/konnichiwa.html',

        coffito: './src/pages/menu/coffito/coffito.html',
        ubeLatte: './src/pages/menu/coffito/ube-latte.html',
        strawberryLatte: './src/pages/menu/coffito/strawberry-latte.html',
        matchaLatte: './src/pages/menu/coffito/matcha-latte.html',
        chocoLatte: './src/pages/menu/coffito/choco-latte.html',
        spanishLatte: './src/pages/menu/coffito/spanish-latte.html',
        caramelCoffee: './src/pages/menu/coffito/caramel-coffee.html',

        colil: './src/pages/menu/colil/colil.html',
        siomai3pcs: './src/pages/menu/colil/siomai-3pcs.html',
        siomai5pcs: './src/pages/menu/colil/siomai-5pcs.html',
        siomaiRice: './src/pages/menu/colil/siomai-rice.html',

        kuyaJong: './src/pages/menu/kuya-jong/kuya-jong.html',
        friedChicken: './src/pages/menu/kuya-jong/fried-chicken.html',
        beefSteak: './src/pages/menu/kuya-jong/beef-steak.html',
        porkMenudo: './src/pages/menu/kuya-jong/pork-menudo.html',
        porkChop: './src/pages/menu/kuya-jong/pork-chop.html',
        chickenAdobo: './src/pages/menu/kuya-jong/chicken-adobo.html',
        friedBangus: './src/pages/menu/kuya-jong/fried-bangus.html',

        santinos: './src/pages/menu/santinos/santinos.html',
        hawaiianMadness: './src/pages/menu/santinos/hawaiian-madness.html',
        pepperoniSorpresa: './src/pages/menu/santinos/pepperoni-sorpresa.html',
        spicyTuna: './src/pages/menu/santinos/spicy-tuna.html',
        baconBonanza: './src/pages/menu/santinos/bacon-bonanza.html',
        chickenHawaiian: './src/pages/menu/santinos/chicken-hawaiian.html',
        barbecueBeef: './src/pages/menu/santinos/barbecue-beef.html',

        titasCatering: './src/pages/menu/titas-catering/titas-catering.html',
        hotsilog: './src/pages/menu/titas-catering/hotsilog.html',
        sinuglaw: './src/pages/menu/titas-catering/sinuglaw.html',
        mamon: './src/pages/menu/titas-catering/mamon.html',
        donut: './src/pages/menu/titas-catering/donut.html',
        crinkles: './src/pages/menu/titas-catering/crinkles.html',
        ensaymada: './src/pages/menu/titas-catering/ensaymada.html',

        topSpatula: './src/pages/menu/top-spatula/top-spatula.html',
        dewberry: './src/pages/menu/top-spatula/dewberry.html',
        skyflakes: './src/pages/menu/top-spatula/skyflakes.html',
        rebisco: './src/pages/menu/top-spatula/rebisco.html',
        gummyWorms: './src/pages/menu/top-spatula/gummy-worms.html',
        nagaraya: './src/pages/menu/top-spatula/nagaraya.html',
        chichacorn: './src/pages/menu/top-spatula/chichacorn.html',

        waffleTime: './src/pages/menu/waffle-time/waffle-time.html',
        americanHotdog: './src/pages/menu/waffle-time/american-hotdog.html',
        hamCheese: './src/pages/menu/waffle-time/ham-cheese.html',
        belgian: './src/pages/menu/waffle-time/belgian.html',
        cheeseDelight: './src/pages/menu/waffle-time/cheese-delight.html',
        bavarian: './src/pages/menu/waffle-time/bavarian.html',
        ultimateUbe: './src/pages/menu/waffle-time/ultimate-ube.html',

        zekiah: './src/pages/menu/zekiah/zekiah.html',
        sisigWithRice: '././src/pages/menu/zekiah/sisig-with-rice.html',
        shrimps: '././src/pages/menu/zekiah/shrimps.html',
        kwek: '././src/pages/menu/zekiah/kwek.html',
        bananaCake: '././src/pages/menu/zekiah/banana-cake.html',
        hotcake: '././src/pages/menu/zekiah/hotcake.html',
        cinnamon: '././src/pages/menu/zekiah/cinnamon.html',
      },
    },
  },
});